language: node_js
node_js:
- '12.13.0'

cache:
  directories:
    - "node_modules"

script:
  # - yarn test
  - yarn build

deploy:
  provider: pages
  github-token: $GITHUB_OAUTH_TOKEN  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: public
  repo: kolenkainc/kolenkainc.github.io
  target-branch: master
  on:
    branch: master
